import { MainPage } from "./pages/main/main-page.js";
customElements.define("main-page", MainPage);
import { LoginPage } from "./pages/login/login-page.js";
customElements.define("login-page", LoginPage);
import { LpmngCard } from "./base/card/lpmng-card.js";
customElements.define("lpmng-card", LpmngCard);
import { LpmngButton } from "./base/button/lpmng-button.js";
customElements.define("lpmng-button", LpmngButton);
import { LpmngTextInput } from "./base/text-input/lpmng-text-input.js";
customElements.define("lpmng-text-input", LpmngTextInput);
import { RegisterPage } from "./pages/register/register-page.js";
customElements.define("register-page", RegisterPage);
import { LpmngCheckbox } from "./base/checkbox/lpmng-checkbox.js";
customElements.define("lpmng-checkbox", LpmngCheckbox);
import { LpmngTable } from "./base/table/lpmng-table.js";
customElements.define("lpmng-table", LpmngTable);
import { NoInternetPage } from "./pages/no-internet/no-internet-page.js";
customElements.define("no-internet-page", NoInternetPage);
import { RouterView } from "./router/view/router-view.js";
customElements.define("router-view", RouterView);
import { RouterLink } from "./router/link/router-link.js";
customElements.define("router-link", RouterLink);
import { MainInternet } from "./pages/main/internet/main-internet.js";
customElements.define("main-internet", MainInternet);
import { AdminPage } from "./pages/admin/admin-page.js";
customElements.define("admin-page", AdminPage);
