[workspace]
resolver = "2"
members = [
  "lpmng-mq",
  "lpmng-core",
  "lpmng-router"
]

[workspace.dependencies]
tokio = "1.41.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }